package generate

import (
	"bytes"
	"fmt"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"

	"opstack-doctor/internal/checks"
	"opstack-doctor/internal/config"
)

type RuleFile struct {
	Groups []RuleGroup `yaml:"groups"`
}

type RuleGroup struct {
	Name  string `yaml:"name"`
	Rules []Rule `yaml:"rules"`
}

type Rule struct {
	Alert       string            `yaml:"alert"`
	Expr        string            `yaml:"expr"`
	For         string            `yaml:"for,omitempty"`
	Labels      map[string]string `yaml:"labels,omitempty"`
	Annotations map[string]string `yaml:"annotations,omitempty"`
}

func Alerts(cfg config.Config) ([]byte, error) {
	cfg.ApplyDefaults()
	sourceSelector := nodeSelector(nodesWithRole(cfg, "source"), "role=\"source\"")
	rules := []Rule{
		{
			Alert:  "OpNodeDown",
			Expr:   "op_node_default_up != 1",
			For:    "2m",
			Labels: map[string]string{"severity": "critical"},
			Annotations: map[string]string{
				"summary":     "op-node is down",
				"description": "op_node_default_up is not 1. Check process health, metrics scrape target, and host networking.",
				"runbook":     "Generated by opstack-doctor. Assumes op-node metrics use the default metric names.",
			},
		},
		{
			Alert:  "L2SafeHeadNotAdvancing",
			Expr:   "increase(op_node_default_refs_number{ref=~\".*safe.*|.*Safe.*\",layer=~\".*l2.*|.*L2.*\"}[10m]) <= 0",
			For:    "10m",
			Labels: map[string]string{"severity": "warning"},
			Annotations: map[string]string{
				"summary":     "L2 safe head is not advancing",
				"description": "Safe-head refs are not increasing. Label names vary; adapt ref/layer selectors to your op-node metrics labels.",
			},
		},
		{
			Alert:  "OpNodeLowPeerCount",
			Expr:   fmt.Sprintf("(op_node_default_peer_count < %.0f) or (op_node_default_p2p_peer_count < %.0f)", cfg.Thresholds.MinPeerCount, cfg.Thresholds.MinPeerCount),
			For:    "5m",
			Labels: map[string]string{"severity": "warning"},
			Annotations: map[string]string{
				"summary":     "op-node peer count is low",
				"description": "P2P peer count is below the configured threshold. Check connectivity, bootnodes, peer limits, and firewalling.",
			},
		},
		{
			Alert:  "OpNodeDerivationErrors",
			Expr:   "increase(op_node_default_derivation_errors_total[5m]) > 0",
			For:    "1m",
			Labels: map[string]string{"severity": "warning"},
			Annotations: map[string]string{
				"summary":     "op-node derivation errors observed",
				"description": "Derivation errors increased. Check L1 RPC health, derivation pipeline logs, and rollup config consistency.",
			},
		},
		{
			Alert:  "OpNodePipelineResets",
			Expr:   "increase(op_node_default_pipeline_resets_total[5m]) > 0",
			For:    "1m",
			Labels: map[string]string{"severity": "warning"},
			Annotations: map[string]string{
				"summary":     "op-node pipeline resets observed",
				"description": "Pipeline resets increased. Check derivation errors, L1 RPC reliability, and source-node stability.",
			},
		},
		{
			Alert:  "SourceOpNodeDown",
			Expr:   "op_node_default_up{" + sourceSelector + "} != 1",
			For:    "2m",
			Labels: map[string]string{"severity": "critical"},
			Annotations: map[string]string{
				"summary":     "source op-node is down",
				"description": "The source tier is a hard dependency for light and sequencer nodes. This rule assumes scrape labels identify source nodes.",
			},
		},
		{
			Alert:  "ProxydEndpointUnhealthy",
			Expr:   "opstack_doctor_finding{id=~\"proxyd\\\\..*\\\\.(rpc|head|chain_id)\",severity=\"fail\"} == 1",
			For:    "2m",
			Labels: map[string]string{"severity": "critical"},
			Annotations: map[string]string{
				"summary":     "proxyd endpoint failed doctor readiness checks",
				"description": "opstack-doctor could not read the configured proxyd RPC endpoint or observed a chain/head failure. Requires scheduled doctor export metrics.",
			},
		},
		{
			Alert:  "DeriverProxydNotConsensusAware",
			Expr:   "opstack_doctor_finding{id=~\"proxyd\\\\..*\\\\.consensus_aware\",severity=\"warn\"} == 1",
			For:    "15m",
			Labels: map[string]string{"severity": "warning"},
			Annotations: map[string]string{
				"summary":     "deriver-tier proxyd is not declared consensus-aware",
				"description": "The OP Labs source/light-node topology recommends consensus-aware proxyd in production. This alert reflects opstack-doctor config intent, not live TOML introspection.",
			},
		},
		{
			Alert:  "ProxydMetricsUnavailable",
			Expr:   "opstack_doctor_finding{id=~\"proxyd\\\\..*\\\\.metrics\",severity=\"warn\"} == 1",
			For:    "10m",
			Labels: map[string]string{"severity": "warning"},
			Annotations: map[string]string{
				"summary":     "proxyd metrics are unavailable",
				"description": "The configured proxyd metrics endpoint is missing or unreachable. Check proxyd Prometheus listener and scrape config.",
			},
		},
		{
			Alert:  "ProxydDown",
			Expr:   "proxyd_up != 1",
			For:    "2m",
			Labels: map[string]string{"severity": "critical"},
			Annotations: map[string]string{
				"summary":     "proxyd is down",
				"description": "proxyd_up is not 1. Check proxyd process health, listener health, and scrape target wiring.",
			},
		},
		{
			Alert:  "ProxydBackendProbeUnhealthy",
			Expr:   "proxyd_backend_probe_healthy == 0",
			For:    "5m",
			Labels: map[string]string{"severity": "warning"},
			Annotations: map[string]string{
				"summary":     "proxyd backend probe is unhealthy",
				"description": "A proxyd backend probe reports unhealthy. Check backend health endpoints, source/light-node processes, and network reachability.",
			},
		},
		{
			Alert:  "ProxydBackendDegradedOrBanned",
			Expr:   "(proxyd_backend_degraded > 0) or (proxyd_consensus_backend_banned > 0)",
			For:    "5m",
			Labels: map[string]string{"severity": "warning"},
			Annotations: map[string]string{
				"summary":     "proxyd backend is degraded or banned",
				"description": "proxyd marked a backend degraded or banned. Check backend latency, error rates, peer count, sync state, latest-block lag, and consensus divergence.",
			},
		},
		{
			Alert:  "ProxydNoConsensusBackends",
			Expr:   "proxyd_group_consensus_count <= 0",
			For:    "2m",
			Labels: map[string]string{"severity": "critical"},
			Annotations: map[string]string{
				"summary":     "proxyd has no serving consensus backends",
				"description": "The consensus-aware backend group has no serving candidates. Check bans, probes, backend sync state, and consensus group filtering.",
			},
		},
		{
			Alert:  "ProxydBackendRequestLatencyHigh",
			Expr:   fmt.Sprintf("proxyd_rpc_backend_request_duration_seconds{quantile=~\"0.9|0.95|0.99\"} > %.3f", cfg.Thresholds.MaxRPCLatencySeconds),
			For:    "5m",
			Labels: map[string]string{"severity": "warning"},
			Annotations: map[string]string{
				"summary":     "proxyd backend request latency is high",
				"description": "Backend request duration quantiles exceed the configured threshold. Check backend node load, network latency, and proxyd timeout settings.",
			},
		},
		{
			Alert:  "ProxydBackendErrorRate",
			Expr:   "proxyd_backend_error_rate > 0",
			For:    "5m",
			Labels: map[string]string{"severity": "warning"},
			Annotations: map[string]string{
				"summary":     "proxyd backend error rate is nonzero",
				"description": "proxyd reports backend request errors. Use request/error counters and backend logs to identify the failing backend and methods.",
			},
		},
		{
			Alert:  "ProxydCLConsensusIssues",
			Expr:   "increase({__name__=~\"proxyd_consensus_cl_(ban_.*|output_root_disagreement_total|no_pin_candidate_total)\"}[5m]) > 0",
			For:    "1m",
			Labels: map[string]string{"severity": "warning"},
			Annotations: map[string]string{
				"summary":     "proxyd CL consensus issue observed",
				"description": "CL/source-tier consensus counters increased. Check op-node backend health, local-safe behavior, output-root agreement, and pin candidate selection.",
			},
		},
		{
			Alert:  "OpSupervisorDown",
			Expr:   "{__name__=~\"op_supervisor_.*_up\"} != 1",
			For:    "2m",
			Labels: map[string]string{"severity": "critical"},
			Annotations: map[string]string{
				"summary":     "op-supervisor is down",
				"description": "op-supervisor up metric is not 1. Check process health, metrics scrape target, and supervisor dependencies.",
			},
		},
		{
			Alert:  "OpSupervisorRefsMissing",
			Expr:   "absent({__name__=~\"op_supervisor_.*_refs_number\"})",
			For:    "10m",
			Labels: map[string]string{"severity": "warning"},
			Annotations: map[string]string{
				"summary":     "op-supervisor refs are missing",
				"description": "Supervisor refs are absent. Confirm op-supervisor metrics are enabled and tracking local/cross safety heads per dependency-set chain.",
			},
		},
		{
			Alert:  "OpSupervisorAccessListVerifyFailures",
			Expr:   "increase({__name__=~\"op_supervisor_.*_access_list_verify_failure\"}[5m]) > 0",
			For:    "1m",
			Labels: map[string]string{"severity": "warning"},
			Annotations: map[string]string{
				"summary":     "op-supervisor access-list verification failures observed",
				"description": "Access-list verification failures increased. Investigate cross-chain message references, dependency-set coverage, and supervisor logs.",
			},
		},
		{
			Alert:  "OpInteropMonitorDown",
			Expr:   "{__name__=~\"op_interop_mon_.*_up\"} != 1",
			For:    "2m",
			Labels: map[string]string{"severity": "critical"},
			Annotations: map[string]string{
				"summary":     "op-interop-mon is down",
				"description": "op-interop-mon up metric is not 1. Check process health and metrics scrape target.",
			},
		},
		{
			Alert:  "OpInteropMonitorRiskyMessages",
			Expr:   "{__name__=~\"op_interop_mon_.*_message_status\",status=~\"invalid|missing|failed|failure|error|unknown\"} > 0",
			For:    "1m",
			Labels: map[string]string{"severity": "warning"},
			Annotations: map[string]string{
				"summary":     "op-interop-mon observed risky message status",
				"description": "Invalid, missing, failed, error, or unknown executing-message statuses are nonzero. Investigate dependency-chain RPC health and message validation.",
			},
		},
		{
			Alert:  "OpInteropMonitorTerminalStatusChanges",
			Expr:   "{__name__=~\"op_interop_mon_.*_terminal_status_changes\"} > 0",
			For:    "1m",
			Labels: map[string]string{"severity": "warning"},
			Annotations: map[string]string{
				"summary":     "op-interop-mon terminal status changes observed",
				"description": "Terminal message status changed. Treat valid/invalid flips as high-signal interop incidents.",
			},
		},
		{
			Alert:  "DoctorInteropDependencyReadinessWarning",
			Expr:   "opstack_doctor_finding{id=~\"interop\\\\..*\\\\.(rpc|chain_id|head|metrics)\",severity=\"warn\"} == 1",
			For:    "5m",
			Labels: map[string]string{"severity": "warning"},
			Annotations: map[string]string{
				"summary":     "interop dependency readiness warning",
				"description": "A scheduled opstack-doctor export found an interop dependency RPC, chain ID, head, or metrics readiness warning. Inspect the finding id and target labels.",
			},
		},
		{
			Alert:  "DoctorInteropSupervisorReadinessFailed",
			Expr:   "opstack_doctor_finding{id=~\"interop\\\\.supervisor\\\\.(metrics_fetch|metrics_names|up|up_missing|refs_missing|expected_chains|ref_types|access_list_verify_failure)\",severity=\"fail\"} == 1",
			For:    "2m",
			Labels: map[string]string{"severity": "critical"},
			Annotations: map[string]string{
				"summary":     "op-supervisor readiness check failed",
				"description": "A scheduled opstack-doctor export observed a failing op-supervisor readiness finding. Inspect the finding id, target, and evidence labels.",
			},
		},
		{
			Alert:  "DoctorInteropSupervisorReadinessWarning",
			Expr:   "opstack_doctor_finding{id=~\"interop\\\\.supervisor\\\\.(metrics_fetch|metrics_names|up|up_missing|refs_missing|expected_chains|ref_types|access_list_verify_failure)\",severity=\"warn\"} == 1",
			For:    "5m",
			Labels: map[string]string{"severity": "warning"},
			Annotations: map[string]string{
				"summary":     "op-supervisor readiness warning",
				"description": "A scheduled opstack-doctor export observed a warning-level op-supervisor readiness finding. Inspect expected chain coverage, refs, and access-list evidence.",
			},
		},
		{
			Alert:  "DoctorInteropMonitorReadinessFailed",
			Expr:   "opstack_doctor_finding{id=~\"interop\\\\.monitor\\\\.(metrics_fetch|metrics_names|up|up_missing|message_status_missing|message_status|terminal_status_changes)\",severity=\"fail\"} == 1",
			For:    "2m",
			Labels: map[string]string{"severity": "critical"},
			Annotations: map[string]string{
				"summary":     "op-interop-mon readiness check failed",
				"description": "A scheduled opstack-doctor export observed a failing op-interop-mon readiness finding. Inspect process health, scrape reachability, and message status evidence.",
			},
		},
		{
			Alert:  "DoctorInteropMonitorReadinessWarning",
			Expr:   "opstack_doctor_finding{id=~\"interop\\\\.monitor\\\\.(metrics_fetch|metrics_names|up|up_missing|message_status_missing|message_status|terminal_status_changes)\",severity=\"warn\"} == 1",
			For:    "5m",
			Labels: map[string]string{"severity": "warning"},
			Annotations: map[string]string{
				"summary":     "op-interop-mon readiness warning",
				"description": "A scheduled opstack-doctor export observed a warning-level op-interop-mon readiness finding. Inspect message status and terminal status change evidence.",
			},
		},
		{
			Alert:  "ExecutionCandidateLaggingReference",
			Expr:   fmt.Sprintf("opstack_doctor_execution_candidate_lag_blocks{chain=%q} > %d", cfg.Chain.Name, cfg.Execution.MaxHeadLagBlocks),
			For:    "5m",
			Labels: map[string]string{"severity": "warning"},
			Annotations: map[string]string{
				"summary":     "execution candidate is lagging reference",
				"description": "Template alert for lag exported by opstack-doctor check --output prometheus or opstack-doctor export metrics.",
			},
		},
		{
			Alert:  "ExecutionBlockComparisonMismatch",
			Expr:   fmt.Sprintf("opstack_doctor_execution_block_compare_match{chain=%q} == 0", cfg.Chain.Name),
			For:    "5m",
			Labels: map[string]string{"severity": "critical"},
			Annotations: map[string]string{
				"summary":     "execution block comparison is failing",
				"description": "opstack-doctor observed mismatched block fields across reference and candidate execution clients.",
			},
		},
		{
			Alert:  "ExecutionRPCSurfaceMismatch",
			Expr:   fmt.Sprintf("opstack_doctor_execution_rpc_surface_match{chain=%q} == 0", cfg.Chain.Name),
			For:    "5m",
			Labels: map[string]string{"severity": "warning"},
			Annotations: map[string]string{
				"summary":     "sampled execution RPC outputs differ",
				"description": "opstack-doctor observed mismatched or unavailable read-only RPC outputs during migration comparison.",
			},
		},
	}
	for _, endpoint := range cfg.Proxyd.Endpoints {
		if endpoint.Name == "" {
			continue
		}
		rules = append(rules, Rule{
			Alert: "ProxydHeadLaggingBackends",
			Expr: fmt.Sprintf(
				"opstack_doctor_proxyd_head_lag_blocks{chain=%q,proxyd=%q} > %d",
				cfg.Chain.Name,
				endpoint.Name,
				cfg.Thresholds.MaxSafeLagBlocks,
			),
			For:    "5m",
			Labels: map[string]string{"severity": "warning", "proxyd": endpoint.Name},
			Annotations: map[string]string{
				"summary":     "proxyd RPC head is lagging declared backends",
				"description": "opstack-doctor observed the proxyd endpoint behind the latest readable backend. Check proxyd backend health and routing strategy.",
			},
		})
	}
	for _, node := range cfg.OPNodes {
		if node.Role != "light" && node.Role != "sequencer" {
			continue
		}
		if node.Follows == "" {
			continue
		}
		rules = append(rules, Rule{
			Alert: "LightNodeLaggingSource",
			Expr: fmt.Sprintf(
				"op_node_default_refs_number{node=%q,ref=~\".*safe.*|.*Safe.*\"} - op_node_default_refs_number{node=%q,ref=~\".*safe.*|.*Safe.*\"} > %d",
				node.Follows,
				node.Name,
				cfg.Thresholds.MaxSafeLagBlocks,
			),
			For:    "5m",
			Labels: map[string]string{"severity": "warning", "node": node.Name, "source": node.Follows},
			Annotations: map[string]string{
				"summary":     "light/sequencer node is lagging its source",
				"description": "Template alert. Assumes Prometheus scrape labels include node and safe-ref labels; adjust selectors to your metric labels.",
			},
		})
	}
	out := RuleFile{Groups: []RuleGroup{{Name: "opstack-doctor.rules", Rules: rules}}}
	return yaml.Marshal(out)
}

func Runbook(cfg config.Config) []byte {
	cfg.ApplyDefaults()
	var b bytes.Buffer
	write := func(format string, args ...any) {
		fmt.Fprintf(&b, format, args...)
	}
	write("# opstack-doctor Runbook: %s\n\n", cfg.Chain.Name)
	write("This runbook is generated from the operator config. It is intentionally read-only: no transaction sending, no private keys, and no mutation steps are required.\n\n")

	write("## op-reth Migration Validation\n\n")
	write("- Run op-reth alongside the existing execution node before migration cutover.\n")
	write("- Compare head block, block hashes, parent hashes, state roots, transaction roots, and receipt roots across at least `%d` latest common blocks.\n", cfg.Execution.CompareBlocks)
	write("- Keep candidate lag under `%d` blocks before moving traffic.\n", cfg.Execution.MaxHeadLagBlocks)
	write("- Treat op-geth as a migration risk: Optimism says op-geth and op-program are supported through May 31, 2026, and operators should migrate to op-reth / cannon-kona.\n")
	write("- After cutover, keep a rollback window and continue comparing sampled RPC outputs.\n\n")

	write("## Source/Light-Node Topology\n\n")
	write("- Maintain a small redundant source tier that performs L1 derivation.\n")
	write("- Configure light and sequencer op-nodes to follow source nodes with `--l2.follow.source=<source op-node RPC>`.\n")
	write("- Production proxyd should be consensus-aware, and dashboards should treat the source tier as a hard dependency.\n")
	write("- Alert when follower safe-head lag exceeds `%d` blocks.\n\n", cfg.Thresholds.MaxSafeLagBlocks)
	write("Configured op-nodes:\n\n")
	for _, node := range cfg.OPNodes {
		follows := node.Follows
		if follows == "" {
			follows = "(none)"
		}
		write("- `%s`: role=%s follows=%s\n", node.Name, node.Role, follows)
	}
	write("\n")

	write("## proxyd / Routing Topology\n\n")
	if !cfg.Proxyd.Enabled {
		write("- proxyd checks are disabled in this config.\n")
		write("- For production source/light-node topology, configure a deriver-tier proxyd endpoint with `consensus_aware: true` and redundant source-node backends.\n\n")
	} else if len(cfg.Proxyd.Endpoints) == 0 {
		write("- proxyd checks are enabled, but no endpoints are configured.\n\n")
	} else {
		write("- Confirm deriver-tier proxyd is consensus-aware and fronts redundant source nodes.\n")
		write("- Confirm edge proxyd fronts light/sequencer nodes for read scaling where applicable.\n")
		write("- Compare proxyd RPC heads with declared backend heads; alert when lag exceeds `%d` blocks.\n\n", cfg.Thresholds.MaxSafeLagBlocks)
		write("Configured proxyd endpoints:\n\n")
		for _, endpoint := range cfg.Proxyd.Endpoints {
			backends := strings.Join(endpoint.ExpectedBackends, ", ")
			if backends == "" {
				backends = "(none)"
			}
			write("- `%s`: role=%s consensus_aware=%t expected_backends=%s\n", endpoint.Name, endpoint.Role, endpoint.ConsensusAware, backends)
		}
		write("\n")
	}

	write("## Interop Dependency Checklist\n\n")
	if !cfg.Interop.Enabled {
		write("- Interop checks are disabled in this config.\n\n")
	} else if len(cfg.Interop.Dependencies) == 0 {
		write("- Interop is enabled, but no dependencies are configured. Add every chain in the dependency set.\n\n")
	} else {
		write("- Verify every dependency chain has reachable RPC and metrics.\n")
		write("- Monitor dependency heads over time; a single diagnostic run only proves reachability.\n")
		write("- Scrape op-supervisor metrics if this operator runs a supervisor; confirm local/cross safety heads cover the configured dependency set.\n")
		write("- Scrape op-interop-mon metrics if this operator runs the optional monitor; alert on invalid/missing messages and terminal status changes.\n")
		write("- This MVP does not validate cross-chain messages or op-supervisor protocol behavior.\n\n")
		write("Configured dependencies:\n\n")
		for _, dep := range cfg.Interop.Dependencies {
			write("- `%s`: chain_id=%d\n", dep.Name, dep.ChainID)
		}
		write("\n")
	}

	write("## Monitoring Checklist\n\n")
	write("- Scrape `op_node_default_up`, `op_node_default_refs_number`, peer count metrics, derivation errors, pipeline resets, and RPC client latency metrics.\n")
	write("- Scrape proxyd metrics such as `proxyd_up`, `proxyd_backend_probe_healthy`, `proxyd_group_consensus_count`, `proxyd_backend_degraded`, `proxyd_consensus_backend_banned`, `proxyd_backend_error_rate`, and `proxyd_rpc_backend_request_duration_seconds`.\n")
	write("- Scrape interop metrics such as `op_supervisor_*_up`, `op_supervisor_*_refs_number`, `op_supervisor_*_access_list_verify_failure`, `op_interop_mon_*_up`, `op_interop_mon_*_message_status`, and `op_interop_mon_*_terminal_status_changes` when those services are deployed.\n")
	write("- Use the generated Prometheus rules as templates; adjust selectors to your actual scrape labels.\n")
	write("- Keep source-tier alerts distinct from light-node capacity alerts.\n")
	write("- Track execution candidate lag via a scheduled doctor run or an equivalent recording rule.\n\n")

	write("## Incident Response\n\n")
	write("### OpNodeDown / SourceOpNodeDown\n\n")
	write("1. Confirm the process and host are alive.\n2. Check the metrics scrape target and op-node logs.\n3. For source nodes, verify dependent light/sequencer nodes have another healthy source to follow.\n\n")
	write("### L2SafeHeadNotAdvancing / LightNodeLaggingSource\n\n")
	write("1. Compare source and follower safe-head metrics.\n2. Check L1 RPC availability and derivation errors.\n3. Verify follow-source configuration and source-node RPC reachability.\n\n")
	write("### ProxydEndpointUnhealthy / ProxydHeadLaggingBackends\n\n")
	write("1. Compare proxyd `eth_blockNumber` with each declared backend.\n2. Check proxyd backend health, consensus-aware routing state, and backend group config.\n3. For deriver proxyd, verify at least two healthy source-node backends are available.\n\n")
	write("### DeriverProxydNotConsensusAware / ProxydMetricsUnavailable\n\n")
	write("1. Inspect proxyd deployment config and confirm consensus-aware routing is enabled where production deriver traffic depends on proxyd.\n2. Verify proxyd Prometheus listener, scrape labels, and dashboard coverage.\n3. Keep doctor config aligned with actual proxyd backend groups; this tool does not introspect private proxyd TOML.\n\n")
	write("### ProxydDown / ProxydBackendProbeUnhealthy\n\n")
	write("1. Confirm proxyd is running and serving both RPC and metrics listeners.\n2. Check backend probe URLs, backend process health, and network policy.\n3. If source-node backends are unhealthy, move dependent light/sequencer nodes to a healthy source-tier endpoint.\n\n")
	write("### ProxydBackendDegradedOrBanned / ProxydNoConsensusBackends\n\n")
	write("1. Inspect proxyd consensus-aware backend state and ban reasons.\n2. Compare backend latest, safe, finalized, peer count, sync state, latency, and error-rate metrics.\n3. Restore at least one healthy backend immediately; for deriver/source tiers, restore redundancy before considering the incident closed.\n\n")
	write("### ProxydBackendRequestLatencyHigh / ProxydBackendErrorRate / ProxydCLConsensusIssues\n\n")
	write("1. Use labels such as `backend_name`, `method_name`, and `backend_group_name` to identify the affected backend and method.\n2. Check backend node logs, disk/network saturation, L1 RPC health, and output-root/local-safe agreement.\n3. Treat increases in CL ban and output-root disagreement counters as source-tier correctness incidents, not just capacity incidents.\n\n")
	write("### OpSupervisorDown / OpSupervisorRefsMissing / OpSupervisorAccessListVerifyFailures\n\n")
	write("1. Confirm op-supervisor is running, metrics are scraped, and the dependency-set config is loaded.\n2. Compare `local_unsafe`, `cross_unsafe`, `local_safe`, and `cross_safe` refs for every expected chain.\n3. Investigate access-list verification failures as cross-chain message correctness incidents.\n\n")
	write("### OpInteropMonitorDown / OpInteropMonitorRiskyMessages / OpInteropMonitorTerminalStatusChanges\n\n")
	write("1. Confirm op-interop-mon is running and connected to each configured chain RPC.\n2. Inspect message status labels for the executing and initiating chain IDs involved.\n3. Treat invalid/missing message statuses or terminal status flips as high-signal interop incidents.\n\n")
	write("### OpNodeLowPeerCount\n\n")
	write("1. Check P2P listen address, advertised address, firewall, and bootnodes.\n2. Confirm peer limits and discovery settings.\n3. Correlate with unsafe-head advancement and derivation health.\n\n")
	write("### OpNodeDerivationErrors / OpNodePipelineResets\n\n")
	write("1. Inspect op-node logs around the alert window.\n2. Check L1 RPC latency/errors and rollup config consistency.\n3. Compare source nodes to distinguish local faults from upstream L1/RPC issues.\n\n")
	write("### ExecutionCandidateLaggingReference\n\n")
	write("1. Compare `eth_blockNumber` on reference and candidate.\n2. Inspect candidate execution logs and disk/network saturation.\n3. Do not cut over until lag and block comparison findings are healthy.\n\n")

	write("## Official References\n\n")
	links := []string{checks.DocOPGethDeprecation, checks.DocLightNodes, checks.DocInterop, checks.DocMetrics, checks.DocProxyd, checks.DocOPSupervisor, checks.DocInteropMonitor}
	sort.Strings(links)
	for _, link := range links {
		write("- %s\n", link)
	}
	return b.Bytes()
}

func nodesWithRole(cfg config.Config, role string) []string {
	var names []string
	for _, node := range cfg.OPNodes {
		if node.Role == role && node.Name != "" {
			names = append(names, node.Name)
		}
	}
	sort.Strings(names)
	return names
}

func nodeSelector(names []string, fallback string) string {
	if len(names) == 0 {
		return fallback
	}
	escaped := make([]string, 0, len(names))
	for _, name := range names {
		escaped = append(escaped, regexpEscape(name))
	}
	return "node=~\"" + strings.Join(escaped, "|") + "\""
}

func regexpEscape(s string) string {
	replacer := strings.NewReplacer(`\`, `\\`, `.`, `\.`, `+`, `\+`, `*`, `\*`, `?`, `\?`, `(`, `\(`, `)`, `\)`, `[`, `\[`, `]`, `\]`, `{`, `\{`, `}`, `\}`, `|`, `\|`, `^`, `\^`, `$`, `\$`)
	return replacer.Replace(s)
}
