package generate

import (
	"bytes"
	"fmt"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"

	"opstack-doctor/internal/checks"
	"opstack-doctor/internal/config"
)

type RuleFile struct {
	Groups []RuleGroup `yaml:"groups"`
}

type RuleGroup struct {
	Name  string `yaml:"name"`
	Rules []Rule `yaml:"rules"`
}

type Rule struct {
	Alert       string            `yaml:"alert"`
	Expr        string            `yaml:"expr"`
	For         string            `yaml:"for,omitempty"`
	Labels      map[string]string `yaml:"labels,omitempty"`
	Annotations map[string]string `yaml:"annotations,omitempty"`
}

func Alerts(cfg config.Config) ([]byte, error) {
	sourceSelector := nodeSelector(nodesWithRole(cfg, "source"), "role=\"source\"")
	rules := []Rule{
		{
			Alert:  "OpNodeDown",
			Expr:   "op_node_default_up != 1",
			For:    "2m",
			Labels: map[string]string{"severity": "critical"},
			Annotations: map[string]string{
				"summary":     "op-node is down",
				"description": "op_node_default_up is not 1. Check process health, metrics scrape target, and host networking.",
				"runbook":     "Generated by opstack-doctor. Assumes op-node metrics use the default metric names.",
			},
		},
		{
			Alert:  "L2SafeHeadNotAdvancing",
			Expr:   "increase(op_node_default_refs_number{ref=~\".*safe.*|.*Safe.*\",layer=~\".*l2.*|.*L2.*\"}[10m]) <= 0",
			For:    "10m",
			Labels: map[string]string{"severity": "warning"},
			Annotations: map[string]string{
				"summary":     "L2 safe head is not advancing",
				"description": "Safe-head refs are not increasing. Label names vary; adapt ref/layer selectors to your op-node metrics labels.",
			},
		},
		{
			Alert:  "OpNodeLowPeerCount",
			Expr:   fmt.Sprintf("(op_node_default_peer_count < %.0f) or (op_node_default_p2p_peer_count < %.0f)", cfg.Thresholds.MinPeerCount, cfg.Thresholds.MinPeerCount),
			For:    "5m",
			Labels: map[string]string{"severity": "warning"},
			Annotations: map[string]string{
				"summary":     "op-node peer count is low",
				"description": "P2P peer count is below the configured threshold. Check connectivity, bootnodes, peer limits, and firewalling.",
			},
		},
		{
			Alert:  "OpNodeDerivationErrors",
			Expr:   "increase(op_node_default_derivation_errors_total[5m]) > 0",
			For:    "1m",
			Labels: map[string]string{"severity": "warning"},
			Annotations: map[string]string{
				"summary":     "op-node derivation errors observed",
				"description": "Derivation errors increased. Check L1 RPC health, derivation pipeline logs, and rollup config consistency.",
			},
		},
		{
			Alert:  "OpNodePipelineResets",
			Expr:   "increase(op_node_default_pipeline_resets_total[5m]) > 0",
			For:    "1m",
			Labels: map[string]string{"severity": "warning"},
			Annotations: map[string]string{
				"summary":     "op-node pipeline resets observed",
				"description": "Pipeline resets increased. Check derivation errors, L1 RPC reliability, and source-node stability.",
			},
		},
		{
			Alert:  "SourceOpNodeDown",
			Expr:   "op_node_default_up{" + sourceSelector + "} != 1",
			For:    "2m",
			Labels: map[string]string{"severity": "critical"},
			Annotations: map[string]string{
				"summary":     "source op-node is down",
				"description": "The source tier is a hard dependency for light and sequencer nodes. This rule assumes scrape labels identify source nodes.",
			},
		},
		{
			Alert:  "ExecutionCandidateLaggingReference",
			Expr:   fmt.Sprintf("opstack_doctor_execution_candidate_lag_blocks{chain=%q} > %d", cfg.Chain.Name, cfg.Execution.MaxHeadLagBlocks),
			For:    "5m",
			Labels: map[string]string{"severity": "warning"},
			Annotations: map[string]string{
				"summary":     "execution candidate is lagging reference",
				"description": "Template alert for lag exported from a scheduled opstack-doctor run or recording rule.",
			},
		},
	}
	for _, node := range cfg.OPNodes {
		if node.Role != "light" && node.Role != "sequencer" {
			continue
		}
		if node.Follows == "" {
			continue
		}
		rules = append(rules, Rule{
			Alert: "LightNodeLaggingSource",
			Expr: fmt.Sprintf(
				"op_node_default_refs_number{node=%q,ref=~\".*safe.*|.*Safe.*\"} - op_node_default_refs_number{node=%q,ref=~\".*safe.*|.*Safe.*\"} > %d",
				node.Follows,
				node.Name,
				cfg.Thresholds.MaxSafeLagBlocks,
			),
			For:    "5m",
			Labels: map[string]string{"severity": "warning", "node": node.Name, "source": node.Follows},
			Annotations: map[string]string{
				"summary":     "light/sequencer node is lagging its source",
				"description": "Template alert. Assumes Prometheus scrape labels include node and safe-ref labels; adjust selectors to your metric labels.",
			},
		})
	}
	out := RuleFile{Groups: []RuleGroup{{Name: "opstack-doctor.rules", Rules: rules}}}
	return yaml.Marshal(out)
}

func Runbook(cfg config.Config) []byte {
	var b bytes.Buffer
	write := func(format string, args ...any) {
		fmt.Fprintf(&b, format, args...)
	}
	write("# opstack-doctor Runbook: %s\n\n", cfg.Chain.Name)
	write("This runbook is generated from the operator config. It is intentionally read-only: no transaction sending, no private keys, and no mutation steps are required.\n\n")

	write("## op-reth Migration Validation\n\n")
	write("- Run op-reth alongside the existing execution node before migration cutover.\n")
	write("- Compare head block, block hashes, parent hashes, state roots, transaction roots, and receipt roots across at least `%d` latest common blocks.\n", cfg.Execution.CompareBlocks)
	write("- Keep candidate lag under `%d` blocks before moving traffic.\n", cfg.Execution.MaxHeadLagBlocks)
	write("- Treat op-geth as a migration risk: Optimism says op-geth and op-program are supported through May 31, 2026, and operators should migrate to op-reth / cannon-kona.\n")
	write("- After cutover, keep a rollback window and continue comparing sampled RPC outputs.\n\n")

	write("## Source/Light-Node Topology\n\n")
	write("- Maintain a small redundant source tier that performs L1 derivation.\n")
	write("- Configure light and sequencer op-nodes to follow source nodes with `--l2.follow.source=<source op-node RPC>`.\n")
	write("- Production proxyd should be consensus-aware, and dashboards should treat the source tier as a hard dependency.\n")
	write("- Alert when follower safe-head lag exceeds `%d` blocks.\n\n", cfg.Thresholds.MaxSafeLagBlocks)
	write("Configured op-nodes:\n\n")
	for _, node := range cfg.OPNodes {
		follows := node.Follows
		if follows == "" {
			follows = "(none)"
		}
		write("- `%s`: role=%s follows=%s\n", node.Name, node.Role, follows)
	}
	write("\n")

	write("## Interop Dependency Checklist\n\n")
	if !cfg.Interop.Enabled {
		write("- Interop checks are disabled in this config.\n\n")
	} else if len(cfg.Interop.Dependencies) == 0 {
		write("- Interop is enabled, but no dependencies are configured. Add every chain in the dependency set.\n\n")
	} else {
		write("- Verify every dependency chain has reachable RPC and metrics.\n")
		write("- Monitor dependency heads over time; a single diagnostic run only proves reachability.\n")
		write("- This MVP does not validate cross-chain messages or op-supervisor protocol behavior.\n\n")
		write("Configured dependencies:\n\n")
		for _, dep := range cfg.Interop.Dependencies {
			write("- `%s`: chain_id=%d\n", dep.Name, dep.ChainID)
		}
		write("\n")
	}

	write("## Monitoring Checklist\n\n")
	write("- Scrape `op_node_default_up`, `op_node_default_refs_number`, peer count metrics, derivation errors, pipeline resets, and RPC client latency metrics.\n")
	write("- Use the generated Prometheus rules as templates; adjust selectors to your actual scrape labels.\n")
	write("- Keep source-tier alerts distinct from light-node capacity alerts.\n")
	write("- Track execution candidate lag via a scheduled doctor run or an equivalent recording rule.\n\n")

	write("## Incident Response\n\n")
	write("### OpNodeDown / SourceOpNodeDown\n\n")
	write("1. Confirm the process and host are alive.\n2. Check the metrics scrape target and op-node logs.\n3. For source nodes, verify dependent light/sequencer nodes have another healthy source to follow.\n\n")
	write("### L2SafeHeadNotAdvancing / LightNodeLaggingSource\n\n")
	write("1. Compare source and follower safe-head metrics.\n2. Check L1 RPC availability and derivation errors.\n3. Verify follow-source configuration and source-node RPC reachability.\n\n")
	write("### OpNodeLowPeerCount\n\n")
	write("1. Check P2P listen address, advertised address, firewall, and bootnodes.\n2. Confirm peer limits and discovery settings.\n3. Correlate with unsafe-head advancement and derivation health.\n\n")
	write("### OpNodeDerivationErrors / OpNodePipelineResets\n\n")
	write("1. Inspect op-node logs around the alert window.\n2. Check L1 RPC latency/errors and rollup config consistency.\n3. Compare source nodes to distinguish local faults from upstream L1/RPC issues.\n\n")
	write("### ExecutionCandidateLaggingReference\n\n")
	write("1. Compare `eth_blockNumber` on reference and candidate.\n2. Inspect candidate execution logs and disk/network saturation.\n3. Do not cut over until lag and block comparison findings are healthy.\n\n")

	write("## Official References\n\n")
	links := []string{checks.DocOPGethDeprecation, checks.DocLightNodes, checks.DocInterop, checks.DocMetrics}
	sort.Strings(links)
	for _, link := range links {
		write("- %s\n", link)
	}
	return b.Bytes()
}

func nodesWithRole(cfg config.Config, role string) []string {
	var names []string
	for _, node := range cfg.OPNodes {
		if node.Role == role && node.Name != "" {
			names = append(names, node.Name)
		}
	}
	sort.Strings(names)
	return names
}

func nodeSelector(names []string, fallback string) string {
	if len(names) == 0 {
		return fallback
	}
	escaped := make([]string, 0, len(names))
	for _, name := range names {
		escaped = append(escaped, regexpEscape(name))
	}
	return "node=~\"" + strings.Join(escaped, "|") + "\""
}

func regexpEscape(s string) string {
	replacer := strings.NewReplacer(`\`, `\\`, `.`, `\.`, `+`, `\+`, `*`, `\*`, `?`, `\?`, `(`, `\(`, `)`, `\)`, `[`, `\[`, `]`, `\]`, `{`, `\{`, `}`, `\}`, `|`, `\|`, `^`, `\^`, `$`, `\$`)
	return replacer.Replace(s)
}
